export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'
export const LOGOUT = 'LOGOUT'
export const SET_DARK_MODE = 'SET_DARK_MODE'
export const SET_LIGHT_MODE = 'SET_LIGHT_MODE'
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'
export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS'
export const GET_PROJECT_BY_ID = 'GET_PROJECT_BY_ID'
export const GET_USER_BY_ID = 'GET_USER_BY_ID'
export const FETCH_TECHNOLOGIES = 'FETCH_TECHNOLOGIES'
export const FILTER_TECHNOLOGIES = 'FILTER_TECHNOLOGIES'
export const FETCH_ERROR = 'FETCH_ERROR';
export const HANDLE_ERROR = 'HANDLE_ERROR';
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const FETCH_USER_BY_ID_REQUEST = 'FETCH_USER_BY_ID_REQUEST';
export const FETCH_USER_BY_ID_SUCCESS= 'FETCH_USER_BY_ID_SUCCESS';
export const FETCH_USER_BY_ID_FAILURE = 'FETCH_USER_BY_ID_FAILURE';
export const FETCH_USER_PROFILE_REQUEST = 'FETCH_USER_PROFILE_REQUEST';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const DELETE_USER_BY_ID_SUCCESS = 'DELETE_USER_BY_ID_SUCCESS';
export const DELETE_USER_BY_ID_FAILURE = 'DELETE_USER_BY_ID_FAILURE';
export const DELETE_USER_PROFILE_SUCCESS = 'DELETE_USER_PROFILE_SUCCESS';
export const DELETE_USER_PROFILE_FAILURE = 'DELETE_USER_PROFILE_FAILURE';
export const GET_PROJECT_BY_ID_REQUEST = 'GET_PROJECT_BY_ID_REQUEST';
export const GET_PROJECT_BY_ID_SUCCESS = 'GET_PROJECT_BY_ID_SUCCESS';
export const GET_PROJECT_BY_ID_FAILURE = 'GET_PROJECT_BY_ID_FAILURE';
















