export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const REGISTER_USER = "REGISTER_USER"
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const FETCH_AUTH_ERROR = 'FETCH_AUTH_ERROR'
export const HANDLE_AUTH_ERROR = 'HANDLE_AUTH_ERROR'
