export const PAYMENT_NOTIFICATION_REQUEST = 'PAYMENT_NOTIFICATION_REQUEST';
export const PAYMENT_NOTIFICATION_SUCCESS = 'PAYMENT_NOTIFICATION_SUCCESS';
export const PAYMENT_NOTIFICATION_FAILURE = 'PAYMENT_NOTIFICATION_FAILURE';