export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_FAILURE = 'GET_REVIEWS_FAILURE';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAILURE = 'DELETE_REVIEW_FAILURE';
export const GET_ALL_REVIEWS = 'GET_ALL_REVIEWS';
export const GET_USER_REVIEWS = 'GET_USER_REVIEWS';
export const CREATE_REVIEW = 'CREATE_REVIEW';

