export const FETCH_TECHNOLOGIES = "FETCH_TECHNOLOGIES";
export const FILTER_TECHNOLOGIES = "FILTER_TECHNOLOGIES"
export const CREATE_TECHNOLOGY_SUCCESS = "CREATE_TECHNOLOGY_SUCCESS"
export const CREATE_TECHNOLOGY_FAILURE = "CREATE_TECHNOLOGY_FAILURE"
